#!/usr/bin/expect -f

set password "440696ar3W!"
set host "root@141.147.147.229"
set timeout 60

spawn ssh -o StrictHostKeyChecking=no $host "curl -I -v http://127.0.0.1:8080; echo '---IPTABLES CHECK---'; iptables-save | grep 8080; iptables -L Docker -n; echo '---LOGS CHECK---'; docker logs --tail 20 sora-proxy-nginx-1"
expect {
    "password:" { send "$password\r" }
    timeout { puts "SSH Timeout"; exit 1 }
}
expect eof
